name: "Members"

on:
  issue_comment:
    types: ["created"]
  workflow_dispatch:

jobs:
  get-members:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'CI')
    runs-on: ubuntu-latest
    name: Get Members
    steps:
      - name: use job
        id: members
        uses: AndrewTwydell/repository-members-action@v1.9
        with:
          token: ${{ secrets.GH_ACTION_PAT }}
          owner: "orbit-software-dev"
          repo: "tester"
      - name: print author
        run: echo ${{ (github.event.comment.author }}
      # - name: get output
      #   run: echo ${{ steps.members.outputs.members }}
